### ISSUE TITLE
Migrate more components to TypeScript

### ISSUE THREAD

**Issue by ricardocasares** [ricardocasares/bemba#8]
Maybe we can do it during hacktoberfest! 🍻

**Comment by ngtungngo** [comment]
Hello,

I would like to work on it

**Comment by ozgunbal** [comment]
Hi @ricardocasares, I already convert `Station` component, but couldn't tested properly. When I start with dev script, no station is fetched and STATIONS/REJECTED action is dispatched.

**Comment by ricardocasares** [comment]
@altaf933 yes! :) Just make sure component props are correctly typed like this [example PR](https://github.com/ricardocasares/bemba/pull/11).

Thank you 🎉!
